env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/tomozo6/ec2ssh/cmd.Version={{.Version}}
      - -X github.com/tomozo6/ec2ssh/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - darwin
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
release:
  prerelease: auto
brew:
brews:
  -
    name: ec2ssh
    github:
      owner: tomozo6
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "ec2ssh is a tool that can easily ssh login to AWS EC2."
    license: "MIT"
    homepage: "https://github.com/tomozo6/ec2ssh"
    install: |
      bin.install "ec2ssh"
    test: |
      system "#{bin}/ec2ssh -h"
