#!/bin/bash

# Arg Check
if [ $# = 0 ]; then
  echo "Usage: ec2ssh [SSHUser]"
  echo "   or: ec2ssh [SSHUser] [GrepWord]"
  exit 1
fi

# Set User
USER=$1

# Set Region
export AWS_DEFAULT_REGION=ap-northeast-1

# Set Opption
OUTPUT="table"
FILTER="Name=instance-state-name,Values=running"
QUERY="sort_by(Reservations[].Instances[].\
                {InstanceId:InstanceId,\
                 Name:Tags[?Key==\`Name\`].Value|[0],\
                 Ip:PrivateIpAddress}[],&Name)"

# Set Command
EC2_DESCRIBE=`aws ec2 describe-instances --output "$OUTPUT" --filter "$FILTER" --query "$QUERY"`

# Main Function
if [ "$2" = "" ]; then

    HOST=`echo "${EC2_DESCRIBE}" | grep -Ei "(Instance|\-{2}|)" | peco | awk -F '|' '{print $3}'`

else

    HOST=`echo "${EC2_DESCRIBE}" | grep -Ei "(Instance|\-{2}|$2|)" | peco | awk -F '|' '{print $3}'`

fi

# Delete Space
HOST=`echo $HOST`

ssh "$USER"@"$HOST"
